#!/usr/bin/env ruby

require 'pixo'
require 'pixo/application'


service_thread = Thread.new do
  sleep 0.1
  Pixo::Ipc::Service.new(STDIN, STDOUT).run
  Pixo::Application.instance.shutdown
end

Pixo::Application.instance.run
